// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.VPNProxyDetector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonProperty("is_vpn")]
        public bool IsVpn { get; set; }

        [JsonProperty("is_datacenter")]
        public bool IsDatacenter { get; set; }

        [JsonProperty("checked_on")]
        public DateTimeOffset CheckedOn { get; set; }

        [JsonProperty("risk_level")]
        public string RiskLevel { get; set; }

        [JsonProperty("threat_level")]
        public string ThreatLevel { get; set; }
    }
}
